# Generated by Django 2.2.13 on 2020-10-25 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='FirstName LastName', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='123456789', max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(default='123456', max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
