# Generated by Django 2.2.13 on 2020-10-25 22:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(default='placeholder.pdf', upload_to=blog.models.user_directory_path),
        ),
    ]
